# Environment variables for all `cargo ...` commands.
[env]

# Scope down tracing, to filter out external lib tracing 
RUST_LOG="axum_course=debug"


## -- Secrets
SERVICE_DB_URL="postgres://app_user:dev_only_pwd@localhost/app_db"


## -- ConfigMap
SERVICE_WEB_FOLDER="web-folder/"
