# Environment variables for all `cargo ...` commands.
[env]

# Scope down tracing, to filter out external lib tracing 
RUST_LOG="axum_course=debug"


## -- ConfigMap

SERVICE_WEB_FOLDER="web-folder/"
